#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
set -e

source $DIR/config

BASE_COMPOSE_FILE="docker-compose.yaml"

if [ "${EMBED_IN_SINGLE_CONTAINER}" == "true" ]; then
   # In case of single container hive needs both derby and hadoop
   BASE_COMPOSE_FILE="docker-compose_single_container_hadoop.yaml"
fi

COMPOSE_ARGS="-f ${BASE_COMPOSE_FILE}"

if [ "${OLK_ENABLED}" == "true" ]; then
   COMPOSE_ARGS="${COMPOSE_ARGS} -f docker-compose_olk.yaml"
fi

docker-compose $COMPOSE_ARGS $@