#!/usr/bin/env bash
export HADOOP_VERSION=3.3.0
export HADOOP_PACKAGE=/home/vinay/releases/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION-RC0.tar.gz

export DERBY_VERSION=10.10.2.0
export DERBY_PACKAGE=/home/vinay/releases/db-derby-10.10.2.0-bin.tar.gz

export HIVE_VERSION=3.1.2
export HIVE_PACKAGE=/home/vinay/releases/apache-hive-3.1.2-bin.tar.gz


export USER_NAME=${USER}
export USER_ID=$(id -u "${USER_NAME}")
export GROUP_ID=$(id -g "${USER_NAME}")